// Committed ambient types for the mobile workspace.
//
// Expo normally writes these into `expo-env.d.ts`, but that file is gitignored and
// only (re)generated by the Expo CLI (e.g. `expo start`). To keep `tsc --noEmit`
// deterministic in CI and on a fresh checkout — without a separate type-generation
// step — we reference Expo's ambient types here (asset + CSS-module module
// declarations, `process.env`, etc.). Referencing the same types from both files is
// idempotent, so this stays correct even after the CLI regenerates `expo-env.d.ts`.
/// <reference types="expo/types" />
